apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090/prometheus
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      httpMethod: GET
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.53.3
      cacheLevel: 'High'
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: prometheus
    secureJsonData:
      httpHeaderValue1: "Bearer"
  
  - name: Google Analytics
    type: grafana-googlesheets-datasource
    access: proxy
    uid: google_analytics
    isDefault: false
    editable: true
    jsonData:
      authType: jwt
      serviceAccountKey: ${GA_SERVICE_ACCOUNT_KEY}
      tokenUri: https://oauth2.googleapis.com/token
      clientEmail: ${GA_CLIENT_EMAIL}
      defaultProjectId: ${GA_PROJECT_ID}
      dataSourceType: googleAnalytics
      propertyId: ${GA_DEV_PROPERTY_ID}
      dateRanges:
        - name: "Last 30 days"
          startDate: "30daysAgo"
          endDate: "today"
        - name: "Last 7 days"
          startDate: "7daysAgo"
          endDate: "today"
        - name: "Yesterday"
          startDate: "yesterday"
          endDate: "yesterday"
