services:
  nginx:
    image: nginx:1.26-alpine
    container_name: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - certbot
    networks:
      - lumina-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/html:/var/www/html
    networks:
      - lumina-network
    # 초기 인증서 발급 후 자동 갱신 설정 (12시간마다 체크)
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  lumina-network:
    external: true