services:
  ai-server:
    container_name: ai-server
    build:
      context: ../../ai
      dockerfile: Dockerfile
    image: rublin322/lumina-ai:develop
    restart: always
    ports:
      - "8000:8000"
    networks:
      - lumina-network
    labels:
      com.docker.compose.service: "ai-server"
      com.docker.compose.project: "lumina"
      environment: "development"

  frontend-blue:
    container_name: frontend-blue
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env.front
    image: rublin322/lumina-frontend:develop
    restart: always
    ports:
      - "3001:80"
    networks:
      - lumina-network
    labels:
      com.docker.compose.service: "frontend-blue"
      com.docker.compose.project: "lumina"
      environment: "development"

  frontend-green:
    container_name: frontend-green
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env.front
    image: rublin322/lumina-frontend:develop
    restart: always
    ports:
      - "3002:80"
    networks:
      - lumina-network
    labels:
      com.docker.compose.service: "frontend-green"
      com.docker.compose.project: "lumina"
      environment: "development"

  backend-blue:
    container_name: backend-blue
    build:
      context: ../../backend
      dockerfile: Dockerfile
    image: rublin322/lumina-backend:develop
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lumina-network
    labels:
      com.docker.compose.service: "backend-blue"
      com.docker.compose.project: "lumina"
      environment: "development"

  backend-green:
    container_name: backend-green
    build:
      context: ../../backend
      dockerfile: Dockerfile
    image: rublin322/lumina-backend:develop
    restart: always
    env_file:
      - .env
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lumina-network
    labels:
      com.docker.compose.service: "backend-green"
      com.docker.compose.project: "lumina"
      environment: "development"

  mysql:
    container_name: mysql
    image: mysql:8.4
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - lumina-network
    labels:
      com.docker.compose.service: "mysql"
      com.docker.compose.project: "lumina"
      environment: "development"

  redis:
    container_name: redis
    image: redis:7.4-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data 
    networks:
      - lumina-network
    labels:
      com.docker.compose.service: "redis"
      com.docker.compose.project: "lumina"
      environment: "development"

volumes:
  mysql-data:
    name: mysql-data
  redis-data:
    name: redis-data

networks:
  lumina-network:
    name: lumina-network
    external: true