services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    user: root
    restart: always
    environment:
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Djenkins.model.JenkinsLocationConfiguration.url=https://picscore.net/jenkins -Djenkins.model.Jenkins.crumbIssuerProxyCompatibility=true -Dhudson.model.DirectoryBrowserSupport.CSP=
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - lumina-network

volumes:
  jenkins_home:
    name: jenkins_home

networks:
  lumina-network:
    external: true